apiVersion: v1
kind: Namespace
metadata:
  name: flappy-game
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: flappy-game
  name: flappy-bird-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flappy-bird
  template:
    metadata:
      labels:
        app: flappy-bird
    spec:
      containers:
        - name: flappy-bird
          image: abhishek8056/flappy-bird:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: flappy-game
  name: flappy-bird-service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: flappy-bird
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: flappy-game
  name: flappy-bird-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flappy-bird-service
                port:
                  number: 80
